import Head from 'next/head'
import Header from '../src/components/Header'
import Navigationbar from '../src/components/Navigationbar'
import Transact from '../src/components/Transact'

export default function Home() {
  return (
    <div className='bg-gradient-to-r from-[#770568] to-[#ca1150]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigationbar/>
      <Header/>
      <Transact/>
    </div>
  )
}
